---
- hosts: 172.31.86.219
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want install webserver
    apt:
      name: apache2
      state: present  
      notify: restartwebserver

  - name: i want to copy static files into ansible nodes  side
    copy:
         src: mystaticfile.html
         dest: /var/www/html/index.html
  
