---
- hosts: all
  become: yes
  tasks: 
  - name: install webservers
    apt:
     name: apache2
     state: present
  - name: i want to start apache2
    service:
     name: apache2
     state: restarted